Add spec for #cut_off
But, spec is faild.

Failures:

  1) Fastladder::Crawler #cut_off when too large feed cut off
       Failure/Error: @logger.info "too large feed:
       #{feed.feedlink}(#{feed.items.size})"

     NameError:
            undefined local variable or method `feed' for
            #<Fastladder::Crawler:0x00005621c92537a8>
                 # ./lib/fastladder/crawler.rb:190:in `cut_off'
                      # ./spec/lib/fastladder/crawler_spec.rb:55:in
            `block (4 levels) in <top (required)>'